### ISSUE TITLE
JS Error with WP 4.1

### ISSUE THREAD

**Issue by jambox** [sewpafly/post-thumbnail-editor#110]
Hey there. I've used this plugin on a ton of sites and it's indispensible...thanks!

However...I just upgraded to WP 4.1 and it seems theres a series of fatal JS errors on the page (both standard and iframe) so nothing loads.

I was seeing this behavior on a WP install I'm currently developing a theme on and thought it might be a plugin/theme conflict or something so I did a fresh 4.1 install and it seems to work. But I'm confused b/c on the install I'm developing with, I've tried disabling all plugins except PTE, saving the permalinks again, changing to twentyfifteen and twentyfourteen and for some reason it still fails. The first error in the JS console is:
```
Uncaught TypeError: undefined is not a functionload-scripts.php?c=1&load[]=jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-resizable,jqu…:114 (anonymous function)load-scripts.php?c=1&load[]=jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-resizable,jqu…:114
```

And then subsequently some require.js errors are triggered:
![screen shot 2014-12-19 at 5 12 11 pm](https://cloud.githubusercontent.com/assets/472818/5512534/656e21e6-87a2-11e4-9797-14e0b0c8222b.png)

I feel like I tried to test what I could and can't figure out whats going on. Myabe a weird version of jQuery is being included or something? I'm gonna roll back to WP 4.0.1 for now, but hopefully you have some insight.

Thanks!

**Comment by sewpafly** [comment]
@kingstringy - Can you disable `WP_DEBUG` and make sure that the debug mode is not enabled to see if the problem persists? (`WP_DEBUG` overrides the PTE setting for debug).  Also, when in debug mode, PTE tries to run the coffeescript straight from the browser unminified.  I probably need to simplify this code, but finding the time is difficult.

**Comment by kingstringy** [comment]
No worries. Just disabled WP_DEBUG and PTE's debug, and PTE seems to be working fine now. (I've been running WP 4.1 the whole time, by the way.)  If I can assist more, let me know. Thanks for the help and the great plugin.

**Comment by tfrommen** [comment]
@sewpafly I can also verify that your plugin seems to work fine when not in debug mode. This is not an actual fix, though. ;)

According to Debug Bar and Firebug, I can share the following errors:

>Error: Mismatched anonymous define() module: ...
>`...c=c[b]});return c}function A(b,c,e,h){c=Error(c+"\nhttp://requirejs.org/docs/err...`
>`-------------------------------------------^`
>
>.../wp-content/plugins/post-thumbnail-editor/apps/requirejs/require.js line 8

This is with `WP_DEBUG` not set, and PTE debug enabled.

When having `WP_DEBUG` set to `TRUE`, I also get the following error:

>TypeError: a is undefined
>`...ight:b.outerHeight(),offset:b.offset()}}a.ui=a.ui||{};var e,f,g=Math.max,h=Math....`
>`-------------------------------------------^`
>
>.../wp-includes/js/jquery/ui/position.min.js?ver=1.11.2 line 11

**Comment by jambox** [comment]
@sewpafly Same experience. I definitely can't develop any WP themes or plugins with `WP_DEBUG` off, so I'd love if you could investigate this. Let me know if I can provide any more info that will help you get to the bottom of it. Thanks!

**Comment by jambox** [comment]
Thanks for working on this! I'll test this week and confirm...

**Comment by sewpafly** [comment]
Hopefully this fixes most of the issues, as I just pushed out to wordpress this version. :smiley:

**Comment by tfrommen** [comment]
Thanks for your work. Unfortunately, I get several errors (as well as warnings), when in debug mode:

![pte_errors](https://cloud.githubusercontent.com/assets/6049306/5718358/a0762486-9b0d-11e4-8693-1488f0e73932.png)

![pte_warnings](https://cloud.githubusercontent.com/assets/6049306/5718364/a7862d02-9b0d-11e4-98db-ff6f90080dce.png)

**Comment by sewpafly** [comment]
@*tfrommen <https://github.com/tfrommen>, what version of firefox are you
using?  I see the same warnings in my firefox, but not the errors.  (Maybe
the download was corrupted somehow?)*

**Comment by sewpafly** [comment]
@tfrommen <https://github.com/tfrommen>, what version of firefox are you
using? I see the same warnings in my firefox, but not the errors. (Maybe
the download was corrupted somehow?)
​

**Comment by tfrommen** [comment]
@sewpafly When I wrote this, it was Firefox 34.0.5. Now it is 35.0, and I still get these errors and warnings.

**Comment by sewpafly** [comment]
@tfrommen - there was still an issue with some plugins that I was having, it didn't have this error message though, so I don't know if 2.4.4 will actually fix it.

**Comment by tfrommen** [comment]
@sewpafly I updated to the latest version but I still get these errors and warnings. I also disabled all other plugins and switched to TwentyThirteen - still the same.

**Comment by jambox** [comment]
Just wanted to chime in and say that everything is working fine for me! I use the latest Chrome on OS X Yosemite.
